# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('user', '0003_auto_20160730_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Classroom'),
            preserve_default=False,
        ),
    ]
