# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Classroom'),
        ),
    ]
